// <auto-generated />
namespace GeniusBar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_order_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_order_status));
        
        string IMigrationMetadata.Id
        {
            get { return "201807250733425_change_order_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
